Add contact form and footer to the page
EidHachem/Portfolio pull request #4
Opened 2022-03-22 15:14 UTC by EidHachem

Add contact section
Add footer with links to social media accounts
Make page mobile friendly

2022-03-22 21:12 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @EidHachem, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![768070f3-bc9a-4aba-b8bc-25793e00ea1e_text](https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif)

## Highlights
✔️ Good commit message
✔️ Good pull request title

## Required 
- [ ] Kindly add collaborators' info in your readme file. 
- [ ] Make sure to add a descriptive PR description.
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-22 21:12 UTC, sja-thedude commented on index.html
> +      </form>
- [ ] Kindly fix the form as it is not submitting.
<img width="615" alt="Screenshot 2022-03-22 at 11 57 58 PM" src="https://user-images.githubusercontent.com/70269507/159574961-7c0c265a-e27f-4c54-bf17-f06a21bdf81d.png">

2022-03-22 21:12 UTC, sja-thedude commented on style.css
>    }
- Kindly remove media for the mobile version. This is used in the desktop version and used as min-width. This gives problems to your code.

2022-03-22 21:12 UTC, sja-thedude commented on style.css
>  }
- [ ] Kindly fix the layout (colours, font, size, space, margins) according to the Figma design. You can open the browser as chrome from vscode and fix it.
- [ ] Kindly add button interactions such as hover, active when pressed according to the Figma design.
- Your design:
<img width="367" alt="Screenshot 2022-03-22 at 11 58 38 PM" src="https://user-images.githubusercontent.com/70269507/159575826-285cccf5-8164-42d2-8b47-d5559f006ff0.png">

- Figma design:
<img width="343" alt="Screenshot 2022-03-23 at 12 05 47 AM" src="https://user-images.githubusercontent.com/70269507/159575946-313154e8-d013-46c2-bc74-37750ff1b0c7.png">

2022-03-23 08:49 UTC, CollinsTatang approved these changes
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 09:27 UTC, merged