Portfolio desktop version
EidHachem/Portfolio pull request #5
Opened 2022-03-24 15:03 UTC by EidHachem

## PR info

- Make the website responsive by:

1.  Adding media queries to style sheet.
2.  Use proper units to achieve responsiveness on different screens sizes

2022-03-24 15:38 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @EidHachem,

Nice job, you are almost there.

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [x] In the mobile view there is a big right margin in the ` works ` section and it will appear more if you make your mobile view width bigger than `375 px` so please fix that and try to stick as much as possible to the given Figma design.

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/159952816-e49a1c32-f21e-4664-b21e-6782e296ca8d.png) | ![image](https://user-images.githubusercontent.com/68796232/159952874-af2f511a-7241-446a-9cdf-a0caf02cf7fe.png)  |

- [x] In the work section in the desktop version please add the right font sizes and font-weights to the text beside the image and fix the height of it too. Kindly fix the image width and height and try to stick as much as possible to the given Figma design.

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/159955058-40142374-24a1-49f1-a3b9-f6d3bb9786a6.png)  | ![image](https://user-images.githubusercontent.com/68796232/159955113-03595af6-8613-4aa3-b17f-932c5a6975d9.png)  |

## [Optional] suggestions:

- [x] Please check the inline comments below.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-03-24 15:38 UTC, omar-muhamad commented on style.css
> +  }
- [x] [Optional] It would be better if you add your desktop styling inside one media query instead of making multiple ones and put it after your mobile styling at the end.

2022-03-25 13:34 UTC, prolajumokeoni approved these changes
Hi @EidHachem, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Check inline comments_



![154919611-7d0675af-6364-45a3-92d6-eccd9b743ced](https://user-images.githubusercontent.com/69638013/160130685-6d631afe-8c49-46cf-be7c-2d19b5bff994.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-25 13:34 UTC, prolajumokeoni commented on index.html
>        <h3 class="work-header">My recent work</h3>
## OPTIONAL
 
Figma Design          |  Your design     
:-------------------------:|:-------------------------:
![anu](https://user-images.githubusercontent.com/69638013/160129304-7f5b8df0-ebb1-4a37-b762-1bdbfed7e1dc.png)  | ![Screenshot_1](https://user-images.githubusercontent.com/69638013/160129477-c25c82f8-4dc3-4796-852e-4ebb771a7328.png)


- [ ] Kindly align the header text on the mobile to look like the figma design
- [ ] Kindly make  all the  horizontal lines on  your project look like the figma design color 👍🏿

2022-03-25 13:37 UTC, merged